import { Feather } from '@expo/vector-icons';
import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { usePawBox } from '@/context/PawBoxContext';

const answerFor = (question: string, petName: string) => {
  const text = question.toLowerCase();
  if (text.includes('food') || text.includes('feed')) return `For ${petName}, start with the feeding guide on the product and adjust for age, weight, and activity. PawBox can suggest products, but a veterinarian should make the final recommendation for medical conditions.`;
  if (text.includes('delivery') || text.includes('run out')) return 'Your current plan is scheduled for Sep 02, 2026. Adjust the delivery rhythm from the Home tab if your pet is eating more or less than expected.';
  if (text.includes('sick') || text.includes('pain') || text.includes('vomit')) return 'I can’t diagnose symptoms or prescribe treatment. If your pet seems seriously unwell, contact a veterinarian promptly or use the Consult a vet option.';
  return 'I can help with general feeding, delivery timing, product questions, and everyday pet-care routines. For urgent or medical concerns, please speak with a veterinarian.';
};

export default function AssistantScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { pet } = usePawBox(); const petName = pet?.name || 'your pet';
  const [question, setQuestion] = useState(''); const [messages, setMessages] = useState<{ from: 'user' | 'ai'; text: string }[]>([{ from: 'ai', text: `Hi, I’m PetCare AI. Ask me anything about ${petName}'s everyday care.` }]);
  const send = () => { if (!question.trim()) return; const next = question.trim(); setMessages((current) => [...current, { from: 'user', text: next }, { from: 'ai', text: answerFor(next, petName) }]); setQuestion(''); };
  return <View style={[styles.page, { backgroundColor: colors.background, paddingTop: insets.top + 18, paddingBottom: insets.bottom }]}><View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>PETCARE AI</Text><Text style={[styles.title, { color: colors.foreground }]}>A little help, anytime.</Text></View><View style={[styles.avatar, { backgroundColor: colors.secondary }]}><Feather name="message-circle" size={20} color={colors.secondaryForeground} /></View></View><ScrollView contentContainerStyle={styles.messages} showsVerticalScrollIndicator={false}>{messages.map((message, index) => <View key={index} style={[styles.bubble, { alignSelf: message.from === 'user' ? 'flex-end' : 'flex-start', backgroundColor: message.from === 'user' ? colors.primary : colors.card, borderColor: colors.border }]}><Text style={[styles.message, { color: message.from === 'user' ? colors.primaryForeground : colors.foreground }]}>{message.text}</Text></View>)}<View style={[styles.safety, { backgroundColor: colors.cream }]}><Feather name="shield" size={16} color={colors.secondaryForeground} /><Text style={[styles.safetyText, { color: colors.secondaryForeground }]}>General guidance only. PetCare AI never diagnoses or prescribes medication.</Text></View></ScrollView><View style={[styles.composer, { borderColor: colors.border, backgroundColor: colors.card }]}><TextInput value={question} onChangeText={setQuestion} onSubmitEditing={send} placeholder="Ask about feeding or care..." placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground }]} returnKeyType="send" /><Pressable onPress={send} style={[styles.send, { backgroundColor: colors.primary }]}><Feather name="arrow-up" size={19} color={colors.primaryForeground} /></Pressable></View></View>;
}

const styles = StyleSheet.create({ page: { flex: 1 }, header: { paddingHorizontal: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }, eyebrow: { fontSize: 12, fontFamily: 'Inter_700Bold', letterSpacing: 1.7 }, title: { fontSize: 27, lineHeight: 32, fontFamily: 'Inter_700Bold', marginTop: 6, maxWidth: 280 }, avatar: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, messages: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 18 }, bubble: { maxWidth: '86%', borderRadius: 19, borderWidth: 1, padding: 14, marginBottom: 11 }, message: { fontSize: 14, lineHeight: 20, fontFamily: 'Inter_400Regular' }, safety: { marginTop: 8, borderRadius: 16, padding: 13, flexDirection: 'row', gap: 9, alignItems: 'flex-start' }, safetyText: { flex: 1, fontSize: 12, lineHeight: 17, fontFamily: 'Inter_600SemiBold' }, composer: { marginHorizontal: 18, marginBottom: 10, minHeight: 58, borderRadius: 17, borderWidth: 1, padding: 7, paddingLeft: 15, flexDirection: 'row', alignItems: 'center' }, input: { flex: 1, fontSize: 14, fontFamily: 'Inter_400Regular', minHeight: 42 }, send: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' } });