import { Feather } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { Pet, PetType, usePawBox } from '@/context/PawBoxContext';

export default function CareScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { pet, pets, addPet, reminders, toggleReminder } = usePawBox();
  const [adding, setAdding] = useState(false); const [name, setName] = useState(''); const [type, setType] = useState<PetType>('dog'); const [age, setAge] = useState('');
  const submit = () => { if (!name.trim() || !age.trim()) return; const next: Pet = { name: name.trim(), type, age: age.trim(), allergies: '' }; addPet(next); setName(''); setAge(''); setAdding(false); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); };
  return <ScrollView style={[styles.page, { backgroundColor: colors.background }]} contentContainerStyle={{ paddingTop: insets.top + 18, paddingBottom: insets.bottom + 100 }}>
    <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>PETCARE</Text><Text style={[styles.title, { color: colors.foreground }]}>Everyday care</Text></View><View style={[styles.avatar, { backgroundColor: colors.secondary }]}><Feather name="heart" size={19} color={colors.secondaryForeground} /></View></View>
    <Text style={[styles.section, { color: colors.foreground }]}>My pets</Text>{(pets.length ? pets : pet ? [pet] : []).map((item, index) => <View key={item.name + index} style={[styles.petCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.petIcon, { backgroundColor: index % 2 ? colors.accent : colors.cream }]}><Feather name={item.type === 'cat' ? 'smile' : 'heart'} size={22} color={colors.foreground} /></View><View style={{ flex: 1 }}><Text style={[styles.petName, { color: colors.foreground }]}>{item.name}</Text><Text style={[styles.body, { color: colors.inkSoft }]}>{item.type} · {item.age} years{item.weight ? ' · ' + item.weight + ' kg' : ''}</Text><Text style={[styles.vet, { color: colors.success }]}>{item.allergies ? 'Allergy notes saved' : 'Profile ready to personalize'}</Text></View><Feather name="chevron-right" size={19} color={colors.mutedForeground} /></View>)}<Pressable onPress={() => setAdding(!adding)} style={[styles.addPet, { borderColor: colors.primary }]}><Feather name={adding ? 'x' : 'plus'} size={18} color={colors.primary} /><Text style={[styles.addText, { color: colors.primary }]}>{adding ? 'Close' : 'Add another pet'}</Text></Pressable>
    {adding && <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.formTitle, { color: colors.foreground }]}>New pet profile</Text><TextInput value={name} onChangeText={setName} placeholder="Pet name" placeholderTextColor={colors.mutedForeground} style={[styles.input, { borderColor: colors.border, color: colors.foreground }]} /><View style={styles.typeRow}>{(['dog', 'cat', 'rabbit'] as PetType[]).map((item) => <Pressable key={item} onPress={() => setType(item)} style={[styles.type, { borderColor: type === item ? colors.primary : colors.border, backgroundColor: type === item ? colors.muted : colors.card }]}><Text style={{ color: type === item ? colors.primary : colors.inkSoft, fontFamily: 'Inter_600SemiBold', fontSize: 12 }}>{item}</Text></Pressable>)}</View><TextInput value={age} onChangeText={setAge} keyboardType="number-pad" placeholder="Age in years" placeholderTextColor={colors.mutedForeground} style={[styles.input, { borderColor: colors.border, color: colors.foreground }]} /><Pressable onPress={submit} style={[styles.primary, { backgroundColor: colors.primary }]}><Text style={styles.primaryText}>Save pet</Text></Pressable></View>}
    <Text style={[styles.section, { color: colors.foreground }]}>Health timeline</Text><View style={[styles.timeline, { backgroundColor: colors.card, borderColor: colors.border }]}>{[['Veterinary consultation', 'Aug 19, 2026', 'activity'], ['Weight updated', 'Aug 12, 2026', 'bar-chart-2'], ['New food recommended', 'Jul 25, 2026', 'package']].map(([title, date, icon]) => <View key={title} style={styles.timelineRow}><View style={[styles.dot, { backgroundColor: colors.primary }]} /><View style={{ flex: 1 }}><Text style={[styles.timelineTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.body, { color: colors.inkSoft }]}>{date}</Text></View><Feather name={icon as 'activity'} size={19} color={colors.primary} /></View>)}</View>
    <Text style={[styles.section, { color: colors.foreground }]}>Reminders</Text>{reminders.map((item) => <Pressable key={item.id} onPress={() => { toggleReminder(item.id); Haptics.selectionAsync(); }} style={[styles.reminder, { backgroundColor: colors.card, borderColor: colors.border, opacity: item.done ? 0.55 : 1 }]}><View style={[styles.check, { borderColor: item.done ? colors.success : colors.border, backgroundColor: item.done ? colors.success : colors.card }]}>{item.done && <Feather name="check" size={14} color={colors.card} />}</View><View style={{ flex: 1 }}><Text style={[styles.timelineTitle, { color: colors.foreground, textDecorationLine: item.done ? 'line-through' : 'none' }]}>{item.title}</Text><Text style={[styles.body, { color: colors.inkSoft }]}>{item.type} · {item.date}</Text></View><Feather name="bell" size={18} color={colors.primary} /></Pressable>)}
  </ScrollView>;
}

const styles = StyleSheet.create({ page: { flex: 1 }, header: { paddingHorizontal: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }, eyebrow: { fontSize: 12, fontFamily: 'Inter_700Bold', letterSpacing: 1.7 }, title: { fontSize: 29, fontFamily: 'Inter_700Bold', marginTop: 6 }, avatar: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, section: { fontSize: 20, fontFamily: 'Inter_700Bold', marginHorizontal: 22, marginTop: 24, marginBottom: 12 }, petCard: { marginHorizontal: 18, padding: 14, borderWidth: 1, borderRadius: 20, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 10 }, petIcon: { width: 50, height: 50, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, petName: { fontSize: 16, fontFamily: 'Inter_700Bold', marginBottom: 3 }, body: { fontSize: 13, lineHeight: 19, fontFamily: 'Inter_400Regular' }, vet: { fontSize: 11, fontFamily: 'Inter_600SemiBold', marginTop: 5 }, addPet: { marginHorizontal: 18, height: 46, borderWidth: 1, borderRadius: 15, borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, addText: { fontSize: 13, fontFamily: 'Inter_700Bold' }, form: { marginHorizontal: 18, marginTop: 12, padding: 15, borderWidth: 1, borderRadius: 18 }, formTitle: { fontSize: 16, fontFamily: 'Inter_700Bold', marginBottom: 10 }, input: { height: 48, borderWidth: 1, borderRadius: 13, paddingHorizontal: 14, marginBottom: 9, fontSize: 14, fontFamily: 'Inter_400Regular' }, typeRow: { flexDirection: 'row', gap: 8, marginBottom: 9 }, type: { flex: 1, height: 40, borderWidth: 1, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, primary: { height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: '#FFFFFF', fontSize: 14, fontFamily: 'Inter_700Bold' }, timeline: { marginHorizontal: 18, borderRadius: 20, borderWidth: 1, padding: 16 }, timelineRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 58, borderBottomWidth: 1, borderBottomColor: '#EADFD3' }, dot: { width: 9, height: 9, borderRadius: 5 }, timelineTitle: { fontSize: 14, fontFamily: 'Inter_700Bold', marginBottom: 2 }, reminder: { marginHorizontal: 18, marginBottom: 9, borderRadius: 16, borderWidth: 1, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 11 }, check: { width: 24, height: 24, borderWidth: 1.5, borderRadius: 12, alignItems: 'center', justifyContent: 'center' } });