import { Feather } from '@expo/vector-icons';
import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { usePawBox } from '@/context/PawBoxContext';

export default function PlansScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { subscription, cancelSubscription } = usePawBox();
  return <ScrollView style={[styles.page, { backgroundColor: colors.background }]} contentContainerStyle={{ paddingTop: insets.top + 18, paddingBottom: insets.bottom + 100 }}>
    <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>MY PAWBOX</Text><Text style={[styles.title, { color: colors.foreground }]}>Your plans</Text></View><View style={[styles.avatar, { backgroundColor: colors.secondary }]}><Feather name="package" size={19} color={colors.secondaryForeground} /></View></View>
    {subscription ? <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.cardTop}><View style={[styles.foodIcon, { backgroundColor: colors.cream }]}><Feather name="package" size={22} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{subscription.foodName}</Text><Text style={[styles.body, { color: colors.inkSoft }]}>{subscription.petName} · {subscription.plan}</Text></View><View style={[styles.activePill, { backgroundColor: colors.accent }]}><Text style={[styles.activeText, { color: colors.accentForeground }]}>Active</Text></View></View><View style={[styles.delivery, { backgroundColor: colors.muted }]}><Feather name="calendar" size={18} color={colors.primary} /><View><Text style={[styles.smallLabel, { color: colors.mutedForeground }]}>NEXT DELIVERY</Text><Text style={[styles.deliveryDate, { color: colors.foreground }]}>{subscription.nextDelivery}</Text></View></View><View style={[styles.cardBottom, { borderTopColor: colors.border }]}><View><Text style={[styles.price, { color: colors.foreground }]}>${subscription.price}<Text style={styles.priceSuffix}> / delivery</Text></Text><Text style={[styles.body, { color: colors.inkSoft }]}>Billed automatically</Text></View><Pressable testID="cancel-subscription" onPress={() => Alert.alert('Pause your plan?', 'You can restart it whenever your pet needs a refill.', [{ text: 'Keep plan', style: 'cancel' }, { text: 'Pause plan', style: 'destructive', onPress: cancelSubscription }])} style={[styles.outlineButton, { borderColor: colors.border }]}><Text style={[styles.outlineText, { color: colors.inkSoft }]}>Pause plan</Text></Pressable></View></View> : <View style={[styles.empty, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.emptyIcon, { backgroundColor: colors.secondary }]}><Feather name="heart" size={24} color={colors.primary} /></View><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Nothing in the bowl yet</Text><Text style={[styles.body, { color: colors.inkSoft, textAlign: 'center' }]}>Build a plan for your pet from the Home tab and we’ll take care of the rest.</Text></View>}
    <View style={[styles.promise, { backgroundColor: colors.cream }]}><Feather name="shield" size={18} color={colors.secondaryForeground} /><Text style={[styles.promiseText, { color: colors.secondaryForeground }]}>Every recipe is thoughtfully reviewed by a veterinarian.</Text></View>
  </ScrollView>;
}

const styles = StyleSheet.create({ page: { flex: 1 }, header: { paddingHorizontal: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 }, eyebrow: { fontSize: 12, fontFamily: 'Inter_700Bold', letterSpacing: 2 }, title: { fontSize: 30, fontFamily: 'Inter_700Bold', marginTop: 6 }, avatar: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, card: { marginHorizontal: 18, borderRadius: 24, borderWidth: 1, padding: 17 }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: 12 }, foodIcon: { width: 52, height: 52, borderRadius: 17, alignItems: 'center', justifyContent: 'center' }, cardTitle: { fontSize: 16, fontFamily: 'Inter_700Bold', marginBottom: 4 }, body: { fontSize: 14, lineHeight: 20, fontFamily: 'Inter_400Regular' }, activePill: { borderRadius: 10, paddingHorizontal: 9, paddingVertical: 5 }, activeText: { fontSize: 11, fontFamily: 'Inter_700Bold' }, delivery: { borderRadius: 16, padding: 14, marginTop: 18, flexDirection: 'row', alignItems: 'center', gap: 11 }, smallLabel: { fontSize: 10, fontFamily: 'Inter_700Bold', letterSpacing: 1 }, deliveryDate: { fontSize: 15, fontFamily: 'Inter_700Bold', marginTop: 3 }, cardBottom: { borderTopWidth: 1, marginTop: 18, paddingTop: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, price: { fontSize: 23, fontFamily: 'Inter_700Bold' }, priceSuffix: { fontSize: 12, fontFamily: 'Inter_400Regular' }, outlineButton: { borderRadius: 13, borderWidth: 1, minHeight: 43, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center' }, outlineText: { fontSize: 12, fontFamily: 'Inter_600SemiBold' }, empty: { marginHorizontal: 18, borderRadius: 24, borderWidth: 1, padding: 30, alignItems: 'center' }, emptyIcon: { width: 60, height: 60, borderRadius: 30, alignItems: 'center', justifyContent: 'center', marginBottom: 14 }, emptyTitle: { fontSize: 19, fontFamily: 'Inter_700Bold', marginBottom: 8 }, promise: { marginHorizontal: 18, marginTop: 18, borderRadius: 18, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 10 }, promiseText: { flex: 1, fontSize: 13, lineHeight: 18, fontFamily: 'Inter_600SemiBold' } });