import { Feather } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import React, { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { usePawBox } from '@/context/PawBoxContext';

const products = [
  { id: 'p1', name: 'Sensitive Stomach Kibble', category: 'Dry food', price: 34, color: '#F7D6B7' },
  { id: 'p2', name: 'Salmon Wellness Bites', category: 'Treats', price: 12, color: '#D9E6D0' },
  { id: 'p3', name: 'Daily Omega Supplement', category: 'Supplements', price: 18, color: '#F5D5CF' },
  { id: 'p4', name: 'Dental Care Chews', category: 'Dental', price: 15, color: '#DDE7C9' },
];

export default function ShopScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { cart, addToCart, removeFromCart } = usePawBox();
  const [search, setSearch] = useState(''); const [showCart, setShowCart] = useState(false);
  const visible = useMemo(() => products.filter((product) => (product.name + product.category).toLowerCase().includes(search.toLowerCase())), [search]);
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const checkout = () => Alert.alert('Demo checkout', 'This sandbox checkout is ready for a payment provider such as M-Pesa or cards. No payment details are stored.');
  return <ScrollView style={[styles.page, { backgroundColor: colors.background }]} contentContainerStyle={{ paddingTop: insets.top + 18, paddingBottom: insets.bottom + 100 }}>
    <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>PAWBOX MARKET</Text><Text style={[styles.title, { color: colors.foreground }]}>Good things for pets.</Text></View><Pressable onPress={() => setShowCart(!showCart)} style={[styles.cartButton, { backgroundColor: colors.secondary }]}><Feather name="shopping-bag" size={20} color={colors.secondaryForeground} />{cart.length > 0 && <View style={[styles.cartBadge, { backgroundColor: colors.primary }]}><Text style={styles.badgeText}>{cart.reduce((sum, item) => sum + item.quantity, 0)}</Text></View>}</Pressable></View>
    <TextInput value={search} onChangeText={setSearch} placeholder="Search food, treats, supplements..." placeholderTextColor={colors.mutedForeground} style={[styles.search, { backgroundColor: colors.card, borderColor: colors.border, color: colors.foreground }]} />
    {showCart ? <View style={[styles.cartCard, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.section, { color: colors.foreground }]}>Your cart</Text>{cart.length === 0 ? <Text style={[styles.body, { color: colors.inkSoft }]}>Your cart is empty.</Text> : <>{cart.map((item) => <View key={item.id} style={styles.cartRow}><View style={{ flex: 1 }}><Text style={[styles.productName, { color: colors.foreground }]}>{item.name}</Text><Text style={[styles.body, { color: colors.inkSoft }]}>${item.price} · qty {item.quantity}</Text></View><Pressable onPress={() => removeFromCart(item.id)}><Feather name="minus-circle" size={20} color={colors.primary} /></Pressable></View>)}<View style={[styles.totalRow, { borderTopColor: colors.border }]}><Text style={[styles.total, { color: colors.foreground }]}>Total</Text><Text style={[styles.total, { color: colors.foreground }]}>${total}</Text></View><Pressable onPress={checkout} style={[styles.primary, { backgroundColor: colors.primary }]}><Text style={styles.primaryText}>Review checkout</Text></Pressable></>}</View> : <>{<Text style={[styles.section, { color: colors.foreground }]}>Shop essentials</Text>}{visible.map((product) => <View key={product.id} style={[styles.product, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.productIcon, { backgroundColor: product.color }]}><Feather name={product.category === 'Treats' ? 'star' : product.category === 'Supplements' ? 'plus' : 'package'} size={22} color={colors.foreground} /></View><View style={{ flex: 1 }}><Text style={[styles.productName, { color: colors.foreground }]}>{product.name}</Text><Text style={[styles.body, { color: colors.inkSoft }]}>{product.category} · ${product.price}</Text></View><Pressable onPress={() => { addToCart({ ...product }); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); }} style={[styles.add, { backgroundColor: colors.muted }]}><Feather name="plus" size={20} color={colors.primary} /></Pressable></View>)}</>}
  </ScrollView>;
}

const styles = StyleSheet.create({ page: { flex: 1 }, header: { paddingHorizontal: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }, eyebrow: { fontSize: 12, fontFamily: 'Inter_700Bold', letterSpacing: 1.7 }, title: { fontSize: 27, lineHeight: 33, fontFamily: 'Inter_700Bold', marginTop: 6, maxWidth: 275 }, cartButton: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center' }, cartBadge: { position: 'absolute', right: -2, top: -2, minWidth: 18, height: 18, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, badgeText: { color: '#FFFFFF', fontSize: 10, fontFamily: 'Inter_700Bold' }, search: { height: 52, borderWidth: 1, borderRadius: 16, marginHorizontal: 18, paddingHorizontal: 16, fontSize: 14, fontFamily: 'Inter_400Regular' }, section: { fontSize: 20, fontFamily: 'Inter_700Bold', marginHorizontal: 22, marginTop: 26, marginBottom: 13 }, product: { marginHorizontal: 18, marginBottom: 12, padding: 13, borderWidth: 1, borderRadius: 19, flexDirection: 'row', alignItems: 'center', gap: 12 }, productIcon: { width: 54, height: 54, borderRadius: 17, alignItems: 'center', justifyContent: 'center' }, productName: { fontSize: 15, fontFamily: 'Inter_700Bold', marginBottom: 4 }, body: { fontSize: 14, lineHeight: 20, fontFamily: 'Inter_400Regular' }, add: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' }, cartCard: { marginHorizontal: 18, borderRadius: 22, borderWidth: 1, padding: 16 }, cartRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, gap: 10 }, totalRow: { borderTopWidth: 1, marginTop: 7, paddingTop: 15, flexDirection: 'row', justifyContent: 'space-between' }, total: { fontSize: 18, fontFamily: 'Inter_700Bold' }, primary: { height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginTop: 16 }, primaryText: { color: '#FFFFFF', fontFamily: 'Inter_700Bold', fontSize: 14 } });